[package]
name = "ronald"
version = "0.1.0"
authors = ["Marc Dominik Migge <marcmigge@gmx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
