[package]
name = "ronald-egui"
version = "0.1.0"
edition = "2024"

[dependencies]
ronald-core = { path = "../ronald-core" }
eframe = { version = "0.31.1", default-features = false, features = [
  "accesskit",
  "default_fonts",
  "persistence",
  "wgpu",
  "x11",
] }
egui_extras = { version = "0.31.1", features = ["svg"] }
serde = "1.0.219"
cpal = "0.16.0"
log = "0.4.27"
