[package]
name = "ronald-egui"
version = "0.2.0"
authors = ["Marc Dominik Migge <marcmigge@gmx.net>"]
license = "MIT"
edition = "2024"

[dependencies]
ronald-core = { path = "../ronald-core" }
anyhow = "1.0"
cpal = { version = "0.18", features = ["wasm-bindgen"] }
directories = "6.0.0"
eframe = { git = "https://github.com/mdm/egui.git", branch = "latest-patched", default-features = false, features = [
  "accesskit",
  "default_fonts",
  "persistence",
  "wgpu",
  "x11",
] }
egui = { git = "https://github.com/mdm/egui.git", branch = "latest-patched" }
egui_extras = { git = "https://github.com/mdm/egui.git", branch = "latest-patched", features = [
  "svg",
] }
hex = "0.4"
log = "0.4"
rfd = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha3 = "0.12"
web-time = "1.1"
wgpu = { version = "29.0", features = ["webgpu", "webgl"] }
zip = "8.6.0"
reqwest = { version = "0.13", features = ["blocking"] }
url = "2.5.8"

# Native-only dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11"
open = "5.3"
walkdir = "2.5"

# Web-only dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
idb = "0.6"
js-sys = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
  "console",
  "Window",
  "Document",
  "Element",
  "HtmlCanvasElement",
  "XmlHttpRequest",
] }

[dev-dependencies]
egui_kittest = { git = "https://github.com/mdm/egui.git", branch = "latest-patched", features = [
  "snapshot",
  "wgpu",
] }
kittest = "0.4"
