use super::KeyLayout;

pub const KEY_LAYOUTS: &[KeyLayout] = &[
    KeyLayout {
        name: "Escape",
        x: 0,
        y: 0,
        width: 100,
        label: include_str!("../../assets/keys/Escape.partial.svg"),
    },
    KeyLayout {
        name: "Key1",
        x: 100,
        y: 0,
        width: 100,
        label: include_str!("../../assets/keys/Key1.partial.svg"),
    },
    KeyLayout {
        name: "Key2",
        x: 200,
        y: 0,
        width: 100,
        label: include_str!("../../assets/keys/Key2.partial.svg"),
    },
    KeyLayout {
        name: "Key3",
        x: 300,
        y: 0,
        width: 100,
        label: include_str!("../../assets/keys/Key3.partial.svg"),
    },
    KeyLayout {
        name: "Key4",
        x: 400,
        y: 0,
        width: 100,
        label: include_str!("../../assets/keys/Key4.partial.svg"),
    },
    KeyLayout {
        name: "Key5",
        x: 500,
        y: 0,
        width: 100,
        label: include_str!("../../assets/keys/Key5.partial.svg"),
    },
    KeyLayout {
        name: "Key6",
        x: 600,
        y: 0,
        width: 100,
        label: include_str!("../../assets/keys/Key6.partial.svg"),
    },
    KeyLayout {
        name: "Key7",
        x: 700,
        y: 0,
        width: 100,
        label: include_str!("../../assets/keys/Key7.partial.svg"),
    },
    KeyLayout {
        name: "Key8",
        x: 800,
        y: 0,
        width: 100,
        label: include_str!("../../assets/keys/Key8.partial.svg"),
    },
    KeyLayout {
        name: "Key9",
        x: 900,
        y: 0,
        width: 100,
        label: include_str!("../../assets/keys/Key9.partial.svg"),
    },
    KeyLayout {
        name: "Key0",
        x: 1000,
        y: 0,
        width: 100,
        label: include_str!("../../assets/keys/Key0.partial.svg"),
    },
    KeyLayout {
        name: "Minus",
        x: 1100,
        y: 0,
        width: 100,
        label: include_str!("../../assets/keys/Minus.partial.svg"),
    },
    KeyLayout {
        name: "Caret",
        x: 1200,
        y: 0,
        width: 100,
        label: include_str!("../../assets/keys/Caret.partial.svg"),
    },
    KeyLayout {
        name: "Clear",
        x: 1300,
        y: 0,
        width: 100,
        label: include_str!("../../assets/keys/Clear.partial.svg"),
    },
    KeyLayout {
        name: "Delete",
        x: 1400,
        y: 0,
        width: 100,
        label: include_str!("../../assets/keys/Delete.partial.svg"),
    },
    KeyLayout {
        name: "Numpad7",
        x: 1500,
        y: 0,
        width: 100,
        label: include_str!("../../assets/keys/Numpad7.partial.svg"),
    },
    KeyLayout {
        name: "Numpad8",
        x: 1600,
        y: 0,
        width: 100,
        label: include_str!("../../assets/keys/Numpad8.partial.svg"),
    },
    KeyLayout {
        name: "Numpad9",
        x: 1700,
        y: 0,
        width: 100,
        label: include_str!("../../assets/keys/Numpad9.partial.svg"),
    },
    KeyLayout {
        name: "JoystickUp",
        x: 2000,
        y: 0,
        width: 100,
        label: include_str!("../../assets/keys/JoystickUp.partial.svg"),
    },
    KeyLayout {
        name: "Tab",
        x: 0,
        y: 100,
        width: 125,
        label: include_str!("../../assets/keys/Tab.partial.svg"),
    },
    KeyLayout {
        name: "Q",
        x: 125,
        y: 100,
        width: 100,
        label: include_str!("../../assets/keys/Q.partial.svg"),
    },
    KeyLayout {
        name: "W",
        x: 225,
        y: 100,
        width: 100,
        label: include_str!("../../assets/keys/W.partial.svg"),
    },
    KeyLayout {
        name: "E",
        x: 325,
        y: 100,
        width: 100,
        label: include_str!("../../assets/keys/E.partial.svg"),
    },
    KeyLayout {
        name: "R",
        x: 425,
        y: 100,
        width: 100,
        label: include_str!("../../assets/keys/R.partial.svg"),
    },
    KeyLayout {
        name: "T",
        x: 525,
        y: 100,
        width: 100,
        label: include_str!("../../assets/keys/T.partial.svg"),
    },
    KeyLayout {
        name: "Y",
        x: 625,
        y: 100,
        width: 100,
        label: include_str!("../../assets/keys/Y.partial.svg"),
    },
    KeyLayout {
        name: "U",
        x: 725,
        y: 100,
        width: 100,
        label: include_str!("../../assets/keys/U.partial.svg"),
    },
    KeyLayout {
        name: "I",
        x: 825,
        y: 100,
        width: 100,
        label: include_str!("../../assets/keys/I.partial.svg"),
    },
    KeyLayout {
        name: "O",
        x: 925,
        y: 100,
        width: 100,
        label: include_str!("../../assets/keys/O.partial.svg"),
    },
    KeyLayout {
        name: "P",
        x: 1025,
        y: 100,
        width: 100,
        label: include_str!("../../assets/keys/P.partial.svg"),
    },
    KeyLayout {
        name: "At",
        x: 1125,
        y: 100,
        width: 100,
        label: include_str!("../../assets/keys/At.partial.svg"),
    },
    KeyLayout {
        name: "BracketLeft",
        x: 1225,
        y: 100,
        width: 100,
        label: include_str!("../../assets/keys/BracketLeft.partial.svg"),
    },
    KeyLayout {
        name: "Enter",
        x: 1325,
        y: 100,
        width: 175,
        label: include_str!("../../assets/keys/Enter.partial.svg"),
    },
    KeyLayout {
        name: "Numpad4",
        x: 1500,
        y: 100,
        width: 100,
        label: include_str!("../../assets/keys/Numpad4.partial.svg"),
    },
    KeyLayout {
        name: "Numpad5",
        x: 1600,
        y: 100,
        width: 100,
        label: include_str!("../../assets/keys/Numpad5.partial.svg"),
    },
    KeyLayout {
        name: "Numpad6",
        x: 1700,
        y: 100,
        width: 100,
        label: include_str!("../../assets/keys/Numpad6.partial.svg"),
    },
    KeyLayout {
        name: "JoystickLeft",
        x: 1900,
        y: 100,
        width: 100,
        label: include_str!("../../assets/keys/JoystickLeft.partial.svg"),
    },
    KeyLayout {
        name: "JoystickRight",
        x: 2100,
        y: 100,
        width: 100,
        label: include_str!("../../assets/keys/JoystickRight.partial.svg"),
    },
    KeyLayout {
        name: "CapsLock",
        x: 0,
        y: 200,
        width: 150,
        label: include_str!("../../assets/keys/CapsLock.partial.svg"),
    },
    KeyLayout {
        name: "A",
        x: 150,
        y: 200,
        width: 100,
        label: include_str!("../../assets/keys/A.partial.svg"),
    },
    KeyLayout {
        name: "S",
        x: 250,
        y: 200,
        width: 100,
        label: include_str!("../../assets/keys/S.partial.svg"),
    },
    KeyLayout {
        name: "D",
        x: 350,
        y: 200,
        width: 100,
        label: include_str!("../../assets/keys/D.partial.svg"),
    },
    KeyLayout {
        name: "F",
        x: 450,
        y: 200,
        width: 100,
        label: include_str!("../../assets/keys/F.partial.svg"),
    },
    KeyLayout {
        name: "G",
        x: 550,
        y: 200,
        width: 100,
        label: include_str!("../../assets/keys/G.partial.svg"),
    },
    KeyLayout {
        name: "H",
        x: 650,
        y: 200,
        width: 100,
        label: include_str!("../../assets/keys/H.partial.svg"),
    },
    KeyLayout {
        name: "J",
        x: 750,
        y: 200,
        width: 100,
        label: include_str!("../../assets/keys/J.partial.svg"),
    },
    KeyLayout {
        name: "K",
        x: 850,
        y: 200,
        width: 100,
        label: include_str!("../../assets/keys/K.partial.svg"),
    },
    KeyLayout {
        name: "L",
        x: 950,
        y: 200,
        width: 100,
        label: include_str!("../../assets/keys/L.partial.svg"),
    },
    KeyLayout {
        name: "Colon",
        x: 1050,
        y: 200,
        width: 100,
        label: include_str!("../../assets/keys/Colon.partial.svg"),
    },
    KeyLayout {
        name: "Semicolon",
        x: 1150,
        y: 200,
        width: 100,
        label: include_str!("../../assets/keys/Semicolon.partial.svg"),
    },
    KeyLayout {
        name: "BracketRight",
        x: 1250,
        y: 200,
        width: 100,
        label: include_str!("../../assets/keys/BracketRight.partial.svg"),
    },
    KeyLayout {
        name: "Numpad1",
        x: 1500,
        y: 200,
        width: 100,
        label: include_str!("../../assets/keys/Numpad1.partial.svg"),
    },
    KeyLayout {
        name: "Numpad2",
        x: 1600,
        y: 200,
        width: 100,
        label: include_str!("../../assets/keys/Numpad2.partial.svg"),
    },
    KeyLayout {
        name: "Numpad3",
        x: 1700,
        y: 200,
        width: 100,
        label: include_str!("../../assets/keys/Numpad3.partial.svg"),
    },
    KeyLayout {
        name: "JoystickDown",
        x: 2000,
        y: 200,
        width: 100,
        label: include_str!("../../assets/keys/JoystickDown.partial.svg"),
    },
    KeyLayout {
        name: "Shift",
        x: 0,
        y: 300,
        width: 200,
        label: include_str!("../../assets/keys/ShiftLeft.partial.svg"),
    },
    KeyLayout {
        name: "Z",
        x: 200,
        y: 300,
        width: 100,
        label: include_str!("../../assets/keys/Z.partial.svg"),
    },
    KeyLayout {
        name: "X",
        x: 300,
        y: 300,
        width: 100,
        label: include_str!("../../assets/keys/X.partial.svg"),
    },
    KeyLayout {
        name: "C",
        x: 400,
        y: 300,
        width: 100,
        label: include_str!("../../assets/keys/C.partial.svg"),
    },
    KeyLayout {
        name: "V",
        x: 500,
        y: 300,
        width: 100,
        label: include_str!("../../assets/keys/V.partial.svg"),
    },
    KeyLayout {
        name: "B",
        x: 600,
        y: 300,
        width: 100,
        label: include_str!("../../assets/keys/B.partial.svg"),
    },
    KeyLayout {
        name: "N",
        x: 700,
        y: 300,
        width: 100,
        label: include_str!("../../assets/keys/N.partial.svg"),
    },
    KeyLayout {
        name: "M",
        x: 800,
        y: 300,
        width: 100,
        label: include_str!("../../assets/keys/M.partial.svg"),
    },
    KeyLayout {
        name: "Comma",
        x: 900,
        y: 300,
        width: 100,
        label: include_str!("../../assets/keys/Comma.partial.svg"),
    },
    KeyLayout {
        name: "Period",
        x: 1000,
        y: 300,
        width: 100,
        label: include_str!("../../assets/keys/Period.partial.svg"),
    },
    KeyLayout {
        name: "Slash",
        x: 1100,
        y: 300,
        width: 100,
        label: include_str!("../../assets/keys/Slash.partial.svg"),
    },
    KeyLayout {
        name: "Backslash",
        x: 1200,
        y: 300,
        width: 100,
        label: include_str!("../../assets/keys/Backslash.partial.svg"),
    },
    KeyLayout {
        name: "Shift",
        x: 1300,
        y: 300,
        width: 200,
        label: include_str!("../../assets/keys/ShiftRight.partial.svg"),
    },
    KeyLayout {
        name: "Numpad0",
        x: 1500,
        y: 300,
        width: 100,
        label: include_str!("../../assets/keys/Numpad0.partial.svg"),
    },
    KeyLayout {
        name: "ArrowUp",
        x: 1600,
        y: 300,
        width: 100,
        label: include_str!("../../assets/keys/ArrowUp.partial.svg"),
    },
    KeyLayout {
        name: "NumpadPeriod",
        x: 1700,
        y: 300,
        width: 100,
        label: include_str!("../../assets/keys/NumpadPeriod.partial.svg"),
    },
    KeyLayout {
        name: "JoystickFire1",
        x: 1900,
        y: 300,
        width: 100,
        label: include_str!("../../assets/keys/JoystickFire1.partial.svg"),
    },
    KeyLayout {
        name: "JoystickFire2",
        x: 2000,
        y: 300,
        width: 100,
        label: include_str!("../../assets/keys/JoystickFire2.partial.svg"),
    },
    KeyLayout {
        name: "JoystickFire3",
        x: 2100,
        y: 300,
        width: 100,
        label: include_str!("../../assets/keys/JoystickFire3.partial.svg"),
    },
    KeyLayout {
        name: "Control",
        x: 0,
        y: 400,
        width: 200,
        label: include_str!("../../assets/keys/Control.partial.svg"),
    },
    KeyLayout {
        name: "Copy",
        x: 200,
        y: 400,
        width: 175,
        label: include_str!("../../assets/keys/Copy.partial.svg"),
    },
    KeyLayout {
        name: "Space",
        x: 375,
        y: 400,
        width: 800,
        label: "",
    },
    KeyLayout {
        name: "NumpadEnter",
        x: 1175,
        y: 400,
        width: 325,
        label: include_str!("../../assets/keys/NumpadEnter.partial.svg"),
    },
    KeyLayout {
        name: "ArrowLeft",
        x: 1500,
        y: 400,
        width: 100,
        label: include_str!("../../assets/keys/ArrowLeft.partial.svg"),
    },
    KeyLayout {
        name: "ArrowDown",
        x: 1600,
        y: 400,
        width: 100,
        label: include_str!("../../assets/keys/ArrowDown.partial.svg"),
    },
    KeyLayout {
        name: "ArrowRight",
        x: 1700,
        y: 400,
        width: 100,
        label: include_str!("../../assets/keys/ArrowRight.partial.svg"),
    },
];

