[package]
name = "ronald-desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
ronald-egui = { path = "../ronald-egui" }
env_logger = "0.11.8"
egui = "0.31.1"
pollster = "0.4.0"
winit = "0.30.11"
egui-winit = "0.31.1"
egui-wgpu = "0.31.1"
